### Adventure Works - Sales & Customer Analysis Practice

#### 1. Import thư viên và dataset

In [ ]:
# import thư viện, file

import pandas as pd 
import numpy as np 
import os 
import re 

path = "D:/DATA/P&G/my_project/_linhtinh/np/data_sales/"

lst_file = os.listdir(path=path)
pattern = r'AdventureWorks_Sales'
frames = []
for name_file in lst_file:
    match = re.match(pattern=pattern, string=name_file)
    if match:
        path_file = path + name_file
        df = pd.read_csv(path_file)
        frames.append(df)
df_combine_sales = pd.concat(frames, axis='rows')
df_combine_sales

In [29]:
# in tên của file trong folder dataset

for file in lst_file:
    print(path + file)

D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Calendar.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Customers.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Products.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Product_Categories.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Product_Subcategories.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Returns.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Sales_2015.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Sales_2016.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Sales_2017.csv
D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Territories.csv


In [31]:
#import các dataset vào dataframe
df_calendar = pd.read_csv('D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Calendar.csv')
df_products = pd.read_csv('D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Products.csv')
df_pro_cate = pd.read_csv('D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Product_Categories.csv')
df_pro_subcate = pd.read_csv('D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Product_Subcategories.csv')
df_returns = pd.read_csv('D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Returns.csv')
df_rerritories = pd.read_csv('D:/DATA/P&G/my_project/_linhtinh/np/data_sales/AdventureWorks_Territories.csv')

#### 2. Exploratory Data

##### Số lượng đơn hàng của từng danh mục sản phẩm

In [38]:
# kiểm tra giá trị của product key ở bảng Sales
df_combine_sales['ProductKey'].unique()


array([332, 312, 350, 338, 310, 314, 345, 313, 351, 344, 326, 348, 311,
       324, 342, 349, 346, 328, 334, 347, 320, 330, 322, 340, 336, 371,
       373, 354, 362, 385, 358, 377, 381, 379, 369, 370, 368, 352, 375,
       387, 360, 356, 383, 389, 479, 606, 529, 486, 540, 541, 530, 571,
       215, 577, 214, 229, 477, 538, 573, 232, 581, 478, 528, 220, 537,
       485, 604, 489, 578, 539, 580, 223, 536, 588, 466, 480, 482, 565,
       605, 596, 462, 560, 464, 593, 576, 488, 584, 490, 487, 562, 583,
       471, 574, 575, 484, 535, 592, 473, 226, 564, 491, 582, 472, 569,
       591, 599, 561, 598, 587, 481, 579, 589, 235, 590, 597, 586, 483,
       566, 475, 476, 585, 600, 595, 594, 474, 572, 563, 568, 567, 570],
      dtype=int64)

In [39]:
#kiểm tra cột product ky trong bảng product
df_products['ProductKey'].unique()

array([214, 215, 218, 219, 220, 223, 226, 229, 232, 235, 238, 241, 244,
       247, 250, 253, 256, 259, 262, 264, 266, 268, 270, 272, 274, 275,
       276, 277, 278, 279, 282, 285, 288, 291, 292, 293, 296, 299, 300,
       301, 304, 307, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
       320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344,
       345, 346, 347, 348, 349, 350, 351, 352, 354, 356, 358, 360, 362,
       364, 365, 366, 367, 368, 369, 370, 371, 373, 375, 377, 379, 381,
       383, 385, 387, 389, 391, 392, 393, 394, 395, 396, 397, 399, 401,
       403, 405, 407, 409, 410, 411, 412, 413, 414, 415, 416, 417, 419,
       420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 431, 433, 435,
       437, 439, 441, 443, 445, 446, 447, 448, 449, 450, 451, 452, 453,
       454, 455, 456, 457, 458, 459, 460, 461, 462, 464, 466, 468, 469,
       470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482,
       483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 49

In [ ]:
#merge của 2 bảng sales và products
df_sale_cate = pd.merge(left=df_combine_sales, right=df_products, on=['ProductKey'], how='left')

In [45]:
# kiểm tra giá trị của Product sub-category key
df_sale_cate['ProductSubcategoryKey'].unique()

array([ 2,  1, 28, 37, 27,  3, 31, 21, 30, 19, 20, 23, 32, 25, 29, 26, 22],
      dtype=int64)

In [46]:
# IN ra 5 dòng đầu tiên của bảng merge ở trên
df_sale_cate.head(5)

OrderDate   StockDate OrderNumber  ProductKey  CustomerKey  TerritoryKey  \
0  1/1/2015   9/21/2001     SO45080         332        14657             1   
1  1/1/2015   12/5/2001     SO45079         312        29255             4   
2  1/1/2015  10/29/2001     SO45082         350        11455             9   
3  1/1/2015  11/16/2001     SO45081         338        26782             6   
4  1/2/2015  12/15/2001     SO45083         312        14947            10   

   OrderLineItem  OrderQuantity  ProductSubcategoryKey  ProductSKU  \
0              1              1                      2  BK-R50B-58   
1              1              1                      2  BK-R93R-48   
2              1              1                      1  BK-M82B-44   
3              1              1                      2  BK-R50B-44   
4              1              1                      2  BK-R93R-48   

              ProductName     ModelName  \
0      Road-650 Black, 58      Road-650   
1        Road-150 Red, 48      Road-150   
2  Mountain-100 Black, 44  Mountain-100   
3      Road-650 Black, 44      Road-650   
4        Road-150 Red, 48      Road-150   

                                  ProductDescription ProductColor ProductSize  \
0  Value-priced bike with many features of our to...        Black          58   
1  This bike is ridden by race winners. Developed...          Red          48   
2  Top-of-the-line competition mountain bike. Per...        Black          44   
3  Value-priced bike with many features of our to...        Black          44   
4  This bike is ridden by race winners. Developed...          Red          48   

  ProductStyle  ProductCost  ProductPrice  
0            U     413.1463      699.0982  
1            U    2171.2942     3578.2700  
2            U    1898.0944     3374.9900  
3            U     413.1463      699.0982  
4            U    2171.2942     3578.2700

In [52]:
# merge 2 bảng sale, produc và category
df_sales_sub_cate = pd.merge(left=df_sale_cate,
                             right=df_pro_subcate,
                             left_on=['ProductSubcategoryKey'],
                             right_on=['ProductCategoryKey'],
                             how='left')
df_sales_sub_cate.head()

OrderDate  StockDate OrderNumber  ProductKey  CustomerKey  TerritoryKey  \
0  1/1/2015  9/21/2001     SO45080         332        14657             1   
1  1/1/2015  9/21/2001     SO45080         332        14657             1   
2  1/1/2015  9/21/2001     SO45080         332        14657             1   
3  1/1/2015  9/21/2001     SO45080         332        14657             1   
4  1/1/2015  9/21/2001     SO45080         332        14657             1   

   OrderLineItem  OrderQuantity  ProductSubcategoryKey_x  ProductSKU  ...  \
0              1              1                        2  BK-R50B-58  ...   
1              1              1                        2  BK-R50B-58  ...   
2              1              1                        2  BK-R50B-58  ...   
3              1              1                        2  BK-R50B-58  ...   
4              1              1                        2  BK-R50B-58  ...   

  ModelName                                 ProductDescription ProductColor  \
0  Road-650  Value-priced bike with many features of our to...        Black   
1  Road-650  Value-priced bike with many features of our to...        Black   
2  Road-650  Value-priced bike with many features of our to...        Black   
3  Road-650  Value-priced bike with many features of our to...        Black   
4  Road-650  Value-priced bike with many features of our to...        Black   

  ProductSize ProductStyle ProductCost  ProductPrice  ProductSubcategoryKey_y  \
0          58            U    413.1463      699.0982                      4.0   
1          58            U    413.1463      699.0982                      5.0   
2          58            U    413.1463      699.0982                      6.0   
3          58            U    413.1463      699.0982                      7.0   
4          58            U    413.1463      699.0982                      8.0   

   SubcategoryName ProductCategoryKey  
0       Handlebars                2.0  
1  Bottom Brackets                2.0  
2           Brakes                2.0  
3           Chains                2.0  
4        Cranksets                2.0  

[5 rows x 21 columns]

In [58]:
# mege tiếp với bảng territories
df_sales_sub_cate_ter = pd.merge(left=df_sales_sub_cate,
                                 right=df_rerritories,
                                 left_on=['TerritoryKey'],
                                 right_on=['SalesTerritoryKey'],
                                 how='left')
df_sales_sub_cate_ter.head()

OrderDate  StockDate OrderNumber  ProductKey  CustomerKey  TerritoryKey  \
0  1/1/2015  9/21/2001     SO45080         332        14657             1   
1  1/1/2015  9/21/2001     SO45080         332        14657             1   
2  1/1/2015  9/21/2001     SO45080         332        14657             1   
3  1/1/2015  9/21/2001     SO45080         332        14657             1   
4  1/1/2015  9/21/2001     SO45080         332        14657             1   

   OrderLineItem  OrderQuantity  ProductSubcategoryKey_x  ProductSKU  ...  \
0              1              1                        2  BK-R50B-58  ...   
1              1              1                        2  BK-R50B-58  ...   
2              1              1                        2  BK-R50B-58  ...   
3              1              1                        2  BK-R50B-58  ...   
4              1              1                        2  BK-R50B-58  ...   

  ProductStyle ProductCost ProductPrice ProductSubcategoryKey_y  \
0            U    413.1463     699.0982                     4.0   
1            U    413.1463     699.0982                     5.0   
2            U    413.1463     699.0982                     6.0   
3            U    413.1463     699.0982                     7.0   
4            U    413.1463     699.0982                     8.0   

   SubcategoryName ProductCategoryKey  SalesTerritoryKey     Region  \
0       Handlebars                2.0                  1  Northwest   
1  Bottom Brackets                2.0                  1  Northwest   
2           Brakes                2.0                  1  Northwest   
3           Chains                2.0                  1  Northwest   
4        Cranksets                2.0                  1  Northwest   

         Country      Continent  
0  United States  North America  
1  United States  North America  
2  United States  North America  
3  United States  North America  
4  United States  North America  

[5 rows x 25 columns]

In [60]:
df_sales_sub_cate_ter_final = pd.merge(left=df_sales_sub_cate_ter,
                                       right=df_pro_cate,
                                       left_on=['ProductCategoryKey'],
                                       right_on=['ProductCategoryKey'],
                                       how='left')

In [68]:
# số lượng đơn hàng, số lượng sản phẩm
df_sales_sub_cate_ter_final.groupby(['CategoryName']).agg({
    'OrderQuantity': 'sum',
    'CustomerKey': 'nunique'
}).rename(columns={
    'OrderQuantity': '#Order',
    'CustomerKey': '#Cust'
})


#Order  #Cust
CategoryName               
Bikes          14118   3950
Clothing       16992   2100
Components     99386   5728

In [69]:
# Số lượng đon hàng và số lượng sản phẩm cảu dategory name=Bikes
df_sales_sub_cate_ter_final[df_sales_sub_cate_ter_final['CategoryName'] == 'Bikes'].groupby(['CategoryName']).agg({
    'OrderQuantity': 'sum',
    'CustomerKey': 'nunique'
}).rename(columns={
    'OrderQuantity': '#Order',
    'CustomerKey': '#Cust'
})

#Order  #Cust
CategoryName               
Bikes          14118   3950

In [71]:
# Lấy số lượng đơn hàng theo tầng quốc gia
df_sales_sub_cate_ter_final.groupby(['Country']).agg({
    'OrderQuantity': 'sum',
    'CustomerKey': 'nunique'
}).rename(columns={
    'OrderQuantity': '#Order',
    'CustomerKey': '#Cust'
})

#Order  #Cust
Country                      
Australia        53675   3480
Canada           17874   1499
France           19397   1705
Germany          20427   1675
United Kingdom   23870   1822
United States    65498   7235

In [75]:
# Số lượng sản phẩm theo country = France và Germany
df_sales_sub_cate_ter_final[(df_sales_sub_cate_ter_final['Country'] == 'France') | (df_sales_sub_cate_ter_final['Country'] == 'Germany')].groupby(['Country']).agg({
    'OrderQuantity': 'sum',
    'CustomerKey': 'nunique'
}).rename(columns={
    'OrderQuantity': '#Order',
    'CustomerKey': '#Cust'
})

#Order  #Cust
Country               
France    19397   1705
Germany   20427   1675