# Numpy

## 1. Khởi tạo mảng trong numpy

In [2]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4],
], dtype=int)

# Đổi kiểu dữ liệu sau khi khởi tạo mảng
a = a.astype(np.float32)
print(a)

[[1. 2.]
 [3. 4.]]


### 1.2 Khởi tạo mảng ngẫu nhiên

In [3]:
r = np.random.randn(2, 3)
print('mảng r: ', '\n', r)

mảng r:  
 [[-1.77224934 -0.39412742 -1.14834996]
 [-0.52880521 -1.17519634  1.17403418]]


#### Loc: Trung bình chính, scale: Phương sai

In [4]:
t = np.random.normal(loc=1, scale=2, size=(2, 3))
print('t', t)

t [[-1.58776828 -3.18631775 -1.99203757]
 [ 1.00784611 -0.34398373 -1.07232497]]


#### low: tạo ra một ma trận phân bổ đều từ low tới high

In [5]:
e = np.random.uniform(low=-1, high=1, size=(2, 3))
print('e', e)

e [[-0.96586614  0.31423763  0.6889771 ]
 [ 0.88988512  0.19315835 -0.48828379]]


#### Tạo 1 ma trận ngẩu nhiên, các phần tử bên trong là int

In [6]:
q = np.random.randint(low=-5, high=5, size=(2, 3))
print('q', q)

q [[ 4  3 -5]
 [-1 -1  0]]


### 1.3 Lưu mảng trên numpy

In [7]:
# S = np.random.randn(3, 3)
#Save file ở dụng npy
# np.save('S_npy', S)
#Save file ở dụng txt
# np.savetxt('S_txt.txt', S)

### 1.4 Truy cập vào file mảng bằng numpy

In [8]:
# V = np.load('S_npy.npy')
# C = np.loadtxt('S_txt.txt')

### 1.5 Convert mảng từ dataframe

In [9]:
# df = pd.read_csv()
#Chuyển từ df sang array numpy để xử lý
# df.values()

### 1.6 Truy cập mảng trên numpy

In [10]:
x = np.array([
	[1, 2, 3, 4],
	[4, 5, 6, 2],
	[7, 8, 9, 1],
	[2, 5, 1, 5]
	])

#Truy cập vào phần tử thuộc dòng 1 cột 2
print(x[1, 2])
#Truy cập vào các dòng từ 1 đến 2 và các cột từ 1 đến 2
print(x[1:3, 1:3])
#Truy cập vào 2 dòng đầu tiên và 2 cột cuối cùng
print(x[:2, -2:])

6
[[5 6]
 [8 9]]
[[3 4]
 [6 2]]


### 1.7 Thay đổi shape của mảng

In [11]:
B = np.array(np.arange(12))
print('B Shape: ', B.shape)
#--Mảng B là một mảng có độ dài là 12
#Thay đổi mảng B thành 2 dòng và 6 cột 
#Để np tự tính số lượng cột B.reshape(4, -1)
C = B.reshape(2, 6)
print(C)
# Cách 2: sử dụng numpy np.reshape()
print(np.reshape(B, (2, 6)))

B Shape:  (12,)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## 2. Các hàm trên numpy

In [12]:
### axis=1 tính theo dòng
### axis=0 tính theo cột

### 2.1 Hàm max, min

In [13]:

b = np.arange(12).reshape(2, -1)
print(b)
# Tìm ra phần tử nhỏ nhất trong B
print(b.min())
print(np.min(b))
# Tìm phần tử nhỏ nhất của b theo dòng
min_value_row = b.min(axis=1)
print(min_value_row)
# Tìm ra phần tử nhỏ nhất theo cột
min_val_col = b.min(axis=0)
print(min_val_col)
# Tìm giá trị lớn nhất của b theo dòng
max_val_row = b.max(axis=1)
print(max_val_row)
# Tìm giá trị trung bình của b theo dòng
mean_val_row = b.mean(axis=1)
print(mean_val_row)
# Tính tổng giá trị của b theo dòng
sum_val_row = b.sum(axis=1)
print(sum_val_row)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
0
0
[0 6]
[0 1 2 3 4 5]
[ 5 11]
[2.5 8.5]
[15 51]


### 2.2 Hàm minimum, maximun: Tìm ra giá trị lớn nhất và nhỏ nhất ở cùng một vị trí giữa 2 mảng cùng kích thước. Kết quả trả về là một mảng có cùng kích thước nhưng có giá trị

In [14]:
# hàm maximum
a = np.array([
	[1, 3, 6],
	[2, 7, 9]
	])

b = np.array([
	[0, 4, 5],
	[1, 6, 10]
	])

# Tìm các phần tử maximum của a, và b cùng vị trí index
print('Các phần tử maximum của a, b cùng index','\n', np.maximum(a, b))
# Tìm các phần tử minimum của a, và b cùng vị trí index
print('Các phần tử minimum của a, b cùng index', '\n', np.minimum(a, b))

Các phần tử maximum của a, b cùng index 
 [[ 1  4  6]
 [ 2  7 10]]
Các phần tử minimum của a, b cùng index 
 [[0 3 5]
 [1 6 9]]


### 2.3 Hàm argmax và argmin thường xuyên được sử dụng trong machine learning vì chúng có tác dụng tìm ra các nhãn có xác suất là cao nhất. Tìm ra index có giá trí lớn nhất của véc tơ

In [15]:
a = np.array([1, 5, 3, 2, 4])
print(np.argmax(a))

a = np.random.randint(1, 10, size=(10))
b = np.random.randint(1, 5, size=(4,2))
print(b)
# Tìm ra index có giá trị lớn nhất
print('index có giá trị lớn nhất của a là: ', np.argmax(a))
print('index có giá trị lớn nhất theo dòng của b là: ', np.argmax(b, axis=1))
print('index có giá trị lớn nhất theo cột của b là: ', np.argmax(b, axis=0))

1
[[2 2]
 [2 1]
 [4 2]
 [1 4]]
index có giá trị lớn nhất của a là:  2
index có giá trị lớn nhất theo dòng của b là:  [0 0 0 1]
index có giá trị lớn nhất theo cột của b là:  [2 3]


### 2.4 Hàm argsort: tìm ra index được sắp xếp theo số thứ tự tăng dần của một mảng hoặc một véc tơ

In [16]:
# np.argsort(array, ascending, axis)

print(np.argsort(b, axis=1))

[[0 1]
 [1 0]
 [1 0]
 [0 1]]


## 3. Các ma trận đặc biệt trong numpy

### 3.1 ma trận đơn vị: là ma trận vuông có các phần tử trên đường chéo bằng 1 và các phần tử còn lại bằng 0. Đây là một ma trận rất đặc biệt vì tích của một ma trận khác với ma trân đơn vị sẽ bằng chính ma trận đó


In [17]:
#khởi tạo ma trân đơn vị vơi shape 5x5
i = np.identity(5, dtype=np.float16)
print(i)

#ma trận 1
a = np.ones((3, 3), dtype=np.float32)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#khởi tạo một ma trận có kích thước 2x3
b = np.random.randn(2, 3)
# khởi tạo ma trận 1 có kích thuocs 2x3
z = np.ones_like(b)
print(z)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#Ma trận 0
#khởi tạo ma trận 0 có kích thước 3x3
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#khởi tạo ma trận 0 có kích thước 2x3
m = np.random.randn(2, 3)
np.zeros_like(m)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
#ma trận đường chính
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
#print đường chéo chính trong mảng ra
g = np.arange(9).reshape(3, 3)
print(g)
print('đường chính của a là: ', '\n', np.diag(g))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
đường chính của a là:  
 [0 4 8]


## 4. Các phép toán và toán tử trên ma trận

### 4.1 Phép toán chuyển vị: Phép toán chuyển vị một ma trận mxn sẽ biến thành một ma trận kích thước nxm sao cho các dòng của ma trận ban đầu sẽ biến thành cột của ma trận chuyển vị

In [23]:
#phép chuyển vị
A = np.arange(12).reshape(3, -1)
print('mảng ban đầu: ', '\n', A)
print('Chuyển vị mảng A: ', '\n', A.T)

mảng ban đầu:  
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Chuyển vị mảng A:  
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 4.2 Ma trận nghịch đảo: ma trận nghịch đảo của một ma trận vuông A khả nghịch là một ma trận được ký hiệu A^^-1. Ma trận này có tích với A là một ma trận đơn vị. A^^-1A = AA^^-1 = I

In [24]:
#Tính ma trận nghịch đảo của A
# pinv là pseudo-inverse of a matrix
A = np.array([
    [1, 2.5, 2],
    [3, 4.2, 1],
    [5, 2.1, 2]
])

A_inv = np.linalg.pinv(A)
print('Inverse A: ', '\n', A_inv)
#Tích của ma trận A với nghịch đảo của nó là một ma trận đơn vị
A.dot(A_inv)

Inverse A:  
 [[-0.24609375  0.03125     0.23046875]
 [ 0.0390625   0.3125     -0.1953125 ]
 [ 0.57421875 -0.40625     0.12890625]]


array([[ 1.00000000e+00,  0.00000000e+00, -4.99600361e-16],
       [ 6.66133815e-16,  1.00000000e+00, -5.82867088e-16],
       [ 0.00000000e+00, -3.33066907e-16,  1.00000000e+00]])

### 4.3 Hạng (rank) của ma trận: Để tìm hiểu hạng ma trận ta làm quen với khái niệm độc lập tuyến tính của hệ véc tơ.
Hạng của ma trận là số lượng các chiều trong không gian véc tơ được sinh ra bởi các cột (hoặc dòng) của ma trận A. Nó chính bằng số lượng lớn nhất của các cột (hoặc dòng) độc lập tuyến tính của ma trận A
np.linalg.matrix_rank(A)

### 4.4 Các phép cộng, trừ: Chúng ta có thể cộng 2 ma trận có cùng kích thước. Các phần tử ở cùng một vị trí ở cả hai ma trận sẽ được cộng hoặc trừ với nhau.

In [25]:
A = np.random.randint(2, 10, size=(3, 4))
B = np.random.randint(3, 10, size=(3, 4))

print('Ma trận A: ', '\n', A)
print('Ma trận B: ', '\n', B)
print('Trừ 2 ma trận', '\n', A - B)
print('Cộng 2 ma trận', '\n', A + B)
print('Nhân 2 ma trận', '\n', A * B)
print('Ma trận A nhân với scael', '\n', A * 5)


Ma trận A:  
 [[9 2 9 5]
 [9 3 2 7]
 [7 4 2 7]]
Ma trận B:  
 [[9 6 3 9]
 [7 3 4 5]
 [5 5 6 5]]
Trừ 2 ma trận 
 [[ 0 -4  6 -4]
 [ 2  0 -2  2]
 [ 2 -1 -4  2]]
Cộng 2 ma trận 
 [[18  8 12 14]
 [16  6  6 12]
 [12  9  8 12]]
Nhân 2 ma trận 
 [[81 12 27 45]
 [63  9  8 35]
 [35 20 12 35]]
Ma trận A nhân với scael 
 [[45 10 45 25]
 [45 15 10 35]
 [35 20 10 35]]


### Bài tập Numpy

#### 1. Tạo một mảng một chiều từ 0 đến 9

In [26]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 2. Tạo một ma trận 3x3 với các giá trị từ 0 đến 8

In [27]:
b = np.random.randint(0, 8, size=(3,3))
b = np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 3. Tính tổng, trung bình, giá trị lớn nhất, giá trị nhỏ nhất của mảng

In [28]:
a = np.arange(10)

print('sum: ', np.sum(a))
print('mean: ', np.mean(a))
print('max: ', np.max(a))
print('min: ', np.min(a))

sum:  45
mean:  4.5
max:  9
min:  0


#### 4. Tính tổng các cột và hàng của ma trận 3x3

In [29]:
b = np.arange(15).reshape(3, -1)

print('mảng 3x3: ', '\n', b)
print('tổng theo hàng: ', np.sum(b, axis=1))
print('tổng theo cột: ', np.sum(b, axis=0))

mảng 3x3:  
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
tổng theo hàng:  [10 35 60]
tổng theo cột:  [15 18 21 24 27]


#### 5. Truy cập phần tử thứ 5 của mảng một chiều

In [30]:
a = np.arange(10)

print('mảng một chiều: ', a)
print('phần tử thứ 5: ', a[4])

mảng một chiều:  [0 1 2 3 4 5 6 7 8 9]
phần tử thứ 5:  4


#### 6. Lây phần slice 2x2 từ ma trận 3x3

In [31]:
b = np.random.randint(0, 15, size=(3,5))

print('mảng 3x3: ', '\n', b)
print('slice 2x2: ', '\n', b[:2, 0:2])

mảng 3x3:  
 [[ 7 12  2  0  6]
 [14  7 14  3  3]
 [ 1  0 12  3 14]]
slice 2x2:  
 [[ 7 12]
 [14  7]]


#### 7. Tính căn bậc 2 của mỗi phần tử trong mảng một chiều

In [32]:
a = np.arange(10)
print('căn bậc 2 của mảng một chiều: ', '\n', np.sqrt(a))

căn bậc 2 của mảng một chiều:  
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


#### 8. Tính lũy thừa 2 của mỗi phần tử trong ma trận 3x3

In [33]:
mang_3x3 = np.arange(9).reshape(3,3)
print('mảng 3x3: ', '\n', mang_3x3)
print('lũy thừa 2 mảng 3x3: ', '\n', np.power(mang_3x3, 2))

mảng 3x3:  
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
lũy thừa 2 mảng 3x3:  
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


#### 9. Tính tích vô hướng của 2 ma trận (dot product)

#### 10. Tính ma trận chuyển vị của ma trận 3x3

In [34]:
mang_3x3 = np.arange(9).reshape(3,3)
print('ma trận 3x3: ', '\n', mang_3x3)
transpose = np.transpose(mang_3x3)
trans = mang_3x3.T
print('Ma trận chuyển vị cách 1: ', '\n', transpose)
print('Ma trận chuyển vị cách 2: ', '\n', trans)

ma trận 3x3:  
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Ma trận chuyển vị cách 1:  
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
Ma trận chuyển vị cách 2:  
 [[0 3 6]
 [1 4 7]
 [2 5 8]]


#### 11. Lấy phần tử lớn hơn 5 từ mảng một chiều

In [35]:
a = np.arange(10)
arr_above_5 = a[a > 5]
print('các phần tử lớn hon 5: ', '\n', arr_above_5)

các phần tử lớn hon 5:  
 [6 7 8 9]


#### 12. Lấy các phần tử trong ma trận 3x3 lớn hơn giá trị trung bình của ma trận

In [36]:
mang_3x3 = np.random.randint(0, 15, size=(3,5))
arr_above_mean = mang_3x3[mang_3x3 > np.mean(mang_3x3)]
print('mảng nguồn: ', '\n', mang_3x3)
print('giá trị trung bình của mảng: ', np.mean(mang_3x3))
print('các phần tử lớn hơn giá trị trung bình của ma trận: ', '\n', arr_above_mean)

mảng nguồn:  
 [[12  1 12  1  3]
 [ 1  4  5  8  5]
 [ 6 12  6 13  5]]
giá trị trung bình của mảng:  6.266666666666667
các phần tử lớn hơn giá trị trung bình của ma trận:  
 [12 12  8 12 13]


#### 13. Tính tích vô hướng của mỗi hàng trong ma trận 3x3 với mảng một chiều [1, 2, 3]

#### 14. Tạo một ma trận 5x5 với các giá trị ngẫu nhiên từ phân phối chuẩn (normal distribution)

In [37]:
random_mtx = np.random.randn(5, 5)
print('ma trận ngẫu nhiên 5x5: ', '\n', random_mtx)

ma trận ngẫu nhiên 5x5:  
 [[-1.0435857  -1.88617159  0.12650987  0.0769673  -0.73474736]
 [ 0.31731138  0.66589776 -1.47466715  2.61644491  0.60892021]
 [ 0.38520596  0.61735887  0.46730073  2.0667314  -0.20818301]
 [-0.75787697 -1.00097979  0.10958583  0.96768464 -0.06753173]
 [-1.20957607  0.15827469  1.13337758 -2.11770751  0.50195841]]


#### 15. Tính trung bình và độ lệch chuẩn của ma trận

In [38]:
a = np.arange(10)
print('giá trị trung bình: ', '\n', np.mean(a))
print('độ lệch chuẩn: ', '\n', np.std(a))

giá trị trung bình:  
 4.5
độ lệch chuẩn:  
 2.8722813232690143


#### 16. Reshape mảng một chiều thành một ma trận 2x5

In [39]:
a = np.arange(10)
a.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 17. Ghép đôi 2 ma trận 2x3 và 2x3 để tạo ma trận 2x6

In [40]:
mtx_2x3_1 = np.random.randint(low=0, high=9, size=(2, 3))
mtx_2x3_2 = np.random.randint(low=10, high=19, size=(2, 3))
noi_mtx_1 = np.concatenate((mtx_2x3_1, mtx_2x3_2), axis=1)
print('cách 1: ', '\n', noi_mtx_1)

cách 1:  
 [[ 8  8  8 14 18 12]
 [ 6  6  0 14 14 13]]


#### 18. Tính định thức của ma trận 3x3

In [41]:
mang_3x3 = np.arange(9).reshape(3,3)
dinhthuc = np.linalg.det(mang_3x3)
print('định thức của ma trận 3x3: ', '\n', dinhthuc)

định thức của ma trận 3x3:  
 0.0
